
<div class="login-box mx-auto">
  <div class="login-logo">
    
  </div>
  <!-- /.login-logo -->
  <div class="card card-outline card-primary">
    <div class="card-header text-center">
      <a href="#" class="h1"><b>Dan-D-Pak</b> MS</a>
    </div>
    <div class="card-body login-card-body">
      <form  method="post" enctype="multipart/form-data" validate="validate">
        <div class="input-group mb-3">
          <input type="text" name="username" class="form-control" placeholder="Username" autocomplete="username" required>
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" name="password" class="form-control" placeholder="Password" autocomplete="current-password" required>
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row mb-2">
          <div class="col-12 col-md-6 text-center">
            <div class="icheck-primary">
              <input type="checkbox" id="remember" name="recall">
              <label for="remember" class="text-primary">
                Ghi nhớ
              </label>
            </div>
          </div>
          <div class="col-12 col-md-6 text-center">
            <label class="text-primary" style="margin: 6px 0;">Hotline: <span class="text-danger">188 {Mỹ}</span></label>
          </div>
        </div>
        <div class="row mb-2">
          <!-- /.col -->
          <div class="col-12">
            <button type="submit" class="btn btn-custom-primary btn-block">Đăng nhập</button>
          </div>
          <!-- /.col -->
        </div>
      </form>
      <!-- /.social-auth-links -->

      <p class="mb-1">
        <a href="<?php echo $this->url('recover-password'); ?>">Quên mật khẩu ?</a>
      </p>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->
