
<div class="login-box mx-auto">
  <div class="login-logo">
    <a href="#"><b>Dan-D-Pak</b> MS</a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">Bạn chỉ còn một bước nữa để có được mật khẩu mới, hãy khôi phục mật khẩu của bạn ngay bây giờ.</p>

      <form method="post">
        <div class="input-group mb-3">
          <input type="hidden" name="code" value="<?php echo isset($_GET['code']) ? $_GET['code'] : ''; ?>">
          <input type="hidden" name="token" value="<?php echo isset($_GET['token']) ? $_GET['token'] : ''; ?>">
          <input type="password" name="password" class="form-control" placeholder="Mật khẩu mới" require minlength="6">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <button type="submit" class="btn btn-custom-primary btn-block">Đổi mật khẩu</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      <p class="mt-3 mb-1">
        <a href="<?php echo $this->url('login'); ?>">Đăng nhập</a>
      </p>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>

