<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
	use Laminas\Authentication\AuthenticationService;
    use Laminas\Session\Container;
    use Manager\Controller\DashboardController;

    /**Get Auth */
    $auth = new AuthenticationService();
    
    /**Get session */
    $containerUser = new Container('user');
    $containerRoute = new Container('route');
    $containerHeader = new Container('HeaderContent');

    /**Get title */
    $title = $this->translate($containerHeader['HeaderTitle']);
    $this->headTitle($this->escapeHtml($title));
    $storage = $auth->getStorage();

    ?>
<!-- layout Application -->
<?php echo $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    
    <?php echo $this->headTitle('Special Coconuts system')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/public/img/layout/favicon.ico'])
        // ->prependStylesheet($this->basePath('public/css/custom.css'))
        ->prependStylesheet($this->basePath('public/css/layout_adm.css'))
        ->prependStylesheet($this->basePath('public/plugins/overlayScrollbars/css/OverlayScrollbars.min.css'))
        ->prependStylesheet($this->basePath('public/plugins/bootstrap-datepicker/dist/css/bootstrap-datetimepicker.min.css'))
        ->prependStylesheet($this->basePath('public/plugins/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css'))
        ->prependStylesheet($this->basePath('public/plugins/clockpicker/css/jquery-clockpicker.min.css'))
        ->prependStylesheet($this->basePath('public/plugins/toastr/toastr.min.css'))
        ->prependStylesheet($this->basePath('public/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css'))
        ->prependStylesheet($this->basePath('public/plugins/flag-icon-css/css/flag-icon.min.css'))
        ->prependStylesheet($this->basePath('public/plugins/fontawesome-free/css/all.min.css'));
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript() ?>
    <script type="text/javascript" src="<?php echo $this->basePath('public/plugins/jquery/jquery.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('public/plugins/moment/moment.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('public/plugins/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('public/plugins/bootstrap-datepicker/dist/js/bootstrap-datetimepicker.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('public/plugins/clockpicker/js/jquery-clockpicker.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('public/js/app.js'); ?>"></script>

    <link href="<?php echo $this->basePath('public/css/custom.css'); ?>" media="screen" rel="stylesheet" type="text/css">
</head>
<body class="hold-transition sidebar-mini layout-fixed sidebar-collapse">
    <div id="pop"></div>
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light navbar-sticky">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
            </ul>
            <?php $button = isset($email) ? '<div class="float-right"><a href="/shipping-services/receive?mail_setting" target="_blank" class="btn  btn-receive-mail"><i class="fas fa-users-cog"></i></a></div><div class="float-right"><a href="/shipping-services/receive?list_content" target="_blank" class="btn  btn-receive-setting"><span class="badge badge-danger navbar-badge">'.$email.'</span><i class="fas fa-mail-bulk"></i></a></div>' : ""; ?>
            <h4 class="m-0 text-dark"> <?php echo $containerHeader['HeaderTitle']; ?> </h4>
            
        </nav>
        <!-- /.navbar -->

        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="<?php echo '#'; ?>" class="brand-link">
                <img src="<?php echo $this->basePath('public/img/layout/Logo.jpg'); ?>" alt="Coconuts Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">Coconuts</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="<?php echo $this->basePath('public/img/user/avatar2.png'); ?>" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="<?php echo '#'; ?>" class="d-block"><?php echo $auth->hasIdentity() ? $containerUser['Fullname'] : 'User'; ?></a>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <li class="nav-item">
                            <a href="<?php echo $this->url('manage-attendance-v2'); ?>" class="nav-link  <?php echo strpos($_SERVER['REQUEST_URI'],'/v2/manage-attendance') !== false ? 'active' : ''; ?>">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>Chấm công tổng hợp</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="<?php echo $this->url('detail-attendance-v2'); ?>" class="nav-link  <?php echo strpos($_SERVER['REQUEST_URI'],'/v2/detail-attendance') !== false ? 'active' : ''; ?>">
                                <i class="nav-icon fas fa-user-clock"></i>
                                <p>Chấm công chi tiết</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="<?php echo $this->url('manage-job-v2'); ?>" class="nav-link  <?php echo strpos($_SERVER['REQUEST_URI'],'/v2/manage-job') !== false ? 'active' : ''; ?>">
                                <i class="nav-icon fas fa-dolly"></i>
                                <p>Công việc</p>
                            </a>
                        </li>
                        <li class="nav-item <?php echo strpos($_SERVER['REQUEST_URI'],'manage-user') !== false ? 'active' : ''; ?>">
                            <a href="<?php echo $this->url('manage-user'); ?>" class="nav-link  <?php echo strpos($_SERVER['REQUEST_URI'],'manage-user') !== false ? 'active' : ''; ?>">
                                <i class="nav-icon fas fa-users"></i>
                                <p>Nhân sự</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="<?php echo $this->url('logout'); ?>" class="nav-link">
                                <i class="nav-icon fas fa-power-off"></i>
                                <p>Đăng xuất</p>
                            </a>
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <?php echo $this->partial('partial/flash.phtml', $this->flashMessenger()); ?>
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->

            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                <!-- Small boxes (Stat box) -->
                <div class="row">
                    <?php echo $this->content; ?>
                </div>
                <!-- /.row -->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
        <strong>Copyright &copy; <?php echo date("Y"); ?>.</strong>
        All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
           <b class="text-info">Version</b> <b><?php echo phpversion(); ?></b>
        </div>
        </footer>
    </div>
    <!-- ./wrapper -->
        <!-- ./wrapper -->  
        <?php echo $this->inlineScript()
            ->prependFile($this->basePath('public/js/custom.js'))
            ->prependFile($this->basePath('public/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js'))
            ->prependFile($this->basePath('public/plugins/toastr/toastr.min.js'))
            ->prependFile($this->basePath('public/plugins/sweetalert2/sweetalert2.min.js'))
            ->prependFile($this->basePath('public/js/jquery.timeago.js'))
            ->prependFile($this->basePath('public/js/app.js'))
            ->prependFile($this->basePath('public/plugins/bootstrap/js/bootstrap.bundle.min.js')) 
            ->prependFile($this->basePath('public/js/bootstrap.min.js')) 
            ->prependFile($this->basePath('public/plugins/popper/umd/popper.min.js')) 
        ?>
        <script type="text/javascript" src="<?php echo $this->basePath('public/js/layout_adm.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('public/js/layout_dm.js'); ?>"></script>
        <script type="text/javascript">
            jQuery(document).ready(function($){
                $('.btn-close').click(function(){
                    $('.notification_all').addClass('d-none');
                });
            });
            
            $(function() {
                $('.mainAlert').fadeOut(10000, function() {
                    $(this).remove();
                });

                $('.timeago').timeago();

                /** if you want to display cool tooltips do this */
                $('[data-toggle="tooltip"]').tooltip({ placement: 'bottom' });

            });
        </script>
    </body>
</html>
