<div class="notification_all popup">
    <div class="noti-content">
        <div class="card">
            <div class="card-header"><h4>Chi tiết <button class="btn btn-sm btn-custom-danger close-upload float-right" onclick="clearAction('action_js')"><i class="fa fa-times-circle pr-2"></i>Đóng</button></h4></div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    <div class="row">
                        <input type="hidden" name="type_post" value="modify_job">
                        <input type="hidden" name="id" value="<?php echo isset($job) ? $job['id'] : ''; ?>">

                        <div class="form-group col-0 col-md-3"></div>
                        <div class="form-group col-12 col-md-3">
                            <label for="job_name">Tên công việc</label>
                            <input type="text" id="job_name" name="job_name" value="<?php echo isset($job) ? $job['job_name'] : ''; ?>" class="text-center form-control">
                        </div>
                        <div class="form-group col-12 col-md-3">
                            <label for="type_works">Ca ngày/đêm</label>
                            <select name="type_works" class="form-control custom-select change-select select2bs4" required>
                                <option <?php echo isset($job['type_works']) && $job['type_works'] == '0' ? 'selected' : ''; ?> value="<?php echo '0'; ?>">Đêm</option>
                                <option <?php echo isset($job['type_works']) && $job['type_works'] == '1' ? 'selected' : ''; ?> value="<?php echo '1'; ?>">Ngày</option>
                                <option <?php echo isset($job['type_works']) && $job['type_works'] == '3' ? 'selected' : ''; ?> value="<?php echo '3'; ?>">Ngày - PT</option>
                            </select>
                        </div>
                        <div class="form-group col-0 col-md-3"></div>
                        <hr>
                        <div class="col-12 text-center mt-3">
                            <button type="submit" class="btn btn-custom-success"><i class="fas fa-upload pr-2"></i>Cập nhật</button>
                        </div>

                    </div>
                </form>
            </div>
        </div>
    </div>
</div>