
<?php
    $this->headLink()
	->prependStylesheet($this->basePath('public/plugins/daterangepicker/daterangepicker.css'))
    ->prependStylesheet($this->basePath('public/plugins/datatables-responsive/css/responsive.bootstrap4.min.css'))
    ->prependStylesheet($this->basePath('public/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css'))
    ->prependStylesheet($this->basePath('public/plugins/select2/css/select2.min.css'))
    ->prependStylesheet($this->basePath('public/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css'));

    use Laminas\Session\Container;
    $containerUser = new Container('user');

    $date = new DateTime();
    $firstDay = date('1-m-Y');
    $lastDay = date("d-m-Y", strtotime('last day of this month'));

    if (isset($_GET['date_report']) && $_GET['date_report'] != '') {
        $date = explode(" - ", $_GET['date_report']);
        $date_from = date("d-m-Y", strtotime(str_replace('/','-', $date[0]))).' 00:00';
        $date_to = date("d-m-Y", strtotime(str_replace('/','-', $date[1]))).' 23:59';
    }
?>

<div id="action_js"></div>
<form method="post" id="update_customer">
    <input type="hidden" name="type_post" value="update_customer">
</form>

<div class="col-12">
    <div class="card card-info">
        <div class="card-body ">
            <form id="form_search" method="get">
                <div class="row">
                    <div class="col-12 col-md-3 form-group"></div>
                    <div class="col-12 col-md-2 form-group">
                        <label for="fullname">Nhân sự</label>
                        <select id="user" name="user" class="form-control custom-select change-select select2bs4">
                            <option value="">---------</option>
                            <?php if ($listUser != null){ foreach ($listUser as $key => $value) { ?>
                                <option <?php echo isset($_GET['user']) && $_GET['user'] == $value['id'] ? 'selected' : ''; ?> value="<?php echo $value['id']; ?>"><?php echo $value['fullname']; ?></option>
                            <?php }} ?>
                        </select>
                    </div>
                    <div class="col-12 col-md-2 form-group">
                        <label for="jobs">Công việc</label>
                        <select id="jobs" name="jobs" class="form-control custom-select change-select select2bs4">
                            <option value="">---------</option>
                            <?php if ($listJob != null){ foreach ($listJob as $key => $value) { ?>
                                <option <?php echo isset($_GET['jobs']) && $_GET['jobs'] == $value['id'] ? 'selected' : ''; ?> value="<?php echo $value['id']; ?>"><?php echo $value['job_name']; ?></option>
                            <?php }} ?>
                        </select>
                    </div>
                    <div class="col-12 col-md-2 form-group">
                        <label for="date_report">Khoảng thời gian</label>
                        <input type="text" id="date_report" name="date_report" value="<?php echo isset($_GET['date_report']) && $_GET['date_report'] != '' ? $_GET['date_report'] : ''; ?>" class="form-control text-center" >
                    </div>
                    <div class="col-12 col-md-3 form-group"></div>
                    
                    <div class="col-12 text-center form-group">
                        <button id="item_search" type="submit" class="btn btn-custom-info  btn-search"><i class="fa fa-search pr-2"></i>Tìm kiếm</button>
                        <div class="btn-group">
                        <button type="button" class="btn btn-custom-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-angle-double-down pr-2"></i>Báo cáo</button>
                        <div class="dropdown-menu">
                            <div class="dropdown-divider"></div>

                            <?php if(isset($data) && count($data) > 0){ ?>
                                <button type="button" class="dropdown-item" onclick="getReportV3('export_summary', '', '1', '')"><i class="fa fa-file-excel pr-2"></i>Excel - Export Summary</button>
                                <div class="dropdown-divider"></div>
                            <?php } ?>
                        </div>
                        </div>
                        <div id="download_div"></div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="col-12">
    <div class="card card-info">
        <div class="card-body">
            <table id="example2" class="table table-bordered table-hover table-like-striped">
                <thead class="vera-middle text-center border-top">
                    <tr>
                        <th>{<span class="text-danger">.<?php echo isset($data) ? count($data) : ''; ?>.</span>} #</th>
                        <th>Tên</th>
                        <th>BHX - BTRE</th>
                        <th>BHX - HCM</th>
                        <th>BHX - Vị Thanh</th>
                        <th>Gà hàng chợ</th>
                        <th>Gà NM</th>
                        <th>Heo</th>
                        <th>Trứng</th>
                        <th>Phụ xe</th>
                        <th>Ngày nghỉ</th>
                        <th>Tổng công</th>
                    </tr>
                </thead>
                <tbody class="text-center">
                    <?php $sumBHX = 0; $total =0; $sumBHXPT = 0; $sumBHXVT = 0; $sumgacho = 0; $sumHeo = 0; $sumWork = 0; $sumOff = 0; $sumPx = 0; 
                     $sumganm = 0; $sumTrung = 0;
                    if (isset($data) && $data != null) { $i=1; foreach ($data as $value){ ?>
                        <tr>
                            <?php $total = $value['sum_bhx'] + $value['sum_bhx_pt'] + $value['sum_bhx_vt'] + $value['sum_ga_cho'] + $value['sum_ga_nm'] + $value['sum_heo'] + $value['sum_trung'] + $value['sum_px'];  ?>
                            <?php $sumWork += $total;  ?>
                            <td>
                                <a href="<?php echo ($this->url('detail-attendance')).'?user='.$value['driver'].'&date_report='.(isset($_GET['date_report']) && $_GET['date_report'] != '' ? $_GET['date_report'] : date("01/m/Y").' - '.date("d/m/Y", strtotime('last day of this month'))); ?>" target="_blank" class="btn btn-xs btn-custom-primary"><i class="fas fa-eye pr-2"></i>Chi tiết</a>
                            </td>
                            <td>
                                <?php echo $value['fullname']; ?>
                                <br>
                                <small class="text-info"><?php echo $value['position']; ?></small>
                            </td>
                            <td><?php echo $value['sum_bhx']; ?></td>
                            <td><?php echo $value['sum_bhx_pt']; ?></td>
                            <td><?php echo $value['sum_bhx_vt']; ?></td>
                            <td><?php echo $value['sum_ga_cho']; ?></td>
                            <td><?php echo $value['sum_ga_nm']; ?></td>
                            <td><?php echo $value['sum_heo']; ?></td>
                            <td><?php echo $value['sum_trung']; ?></td>
                            <td><?php echo $value['sum_px']; ?></td>
                            <td><?php echo $value['sum_off']; ?></td>
                            <td><?php echo $total; ?></td>
                        </tr>
                    <?php $i++; $sumBHX += $value['sum_bhx']; $sumBHXPT += $value['sum_bhx_pt']; $sumgacho += $value['sum_ga_cho']; 
                    $sumBHXVT += $value['sum_bhx_vt'];
                    $sumganm += $value['sum_ga_nm']; $sumHeo += $value['sum_heo']; $sumTrung += $value['sum_trung']; $sumOff += $value['sum_off']; $sumPx += $value['sum_px']; }} ?>
                </tbody>
                <tfoot>
                    <tr class="bg-bisque text-danger text-bold text-center">
                        <td></td>
                        <td></td>
                        <td><?php echo $sumBHX; ?></td>
                        <td><?php echo $sumBHXPT; ?></td>
                        <td><?php echo $sumBHXVT; ?></td>
                        <td><?php echo $sumgacho; ?></td>
                        <td><?php echo $sumganm; ?></td>
                        <td><?php echo $sumHeo; ?></td>
                        <td><?php echo $sumTrung; ?></td>
                        <td><?php echo $sumPx; ?></td>
                        <td><?php echo $sumOff; ?></td>
                        <td><?php echo $sumWork; ?></td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>



<!-- Page specific script -->
<script type="text/javascript">
    jQuery(document).ready(function($){
        //Initialize Select2 Elements
        $('.select2').select2();

        $('.select2bs4').select2({
            theme: 'bootstrap4'
        })

        $('#example2').DataTable({
            "paging": true,
            "pageLength": 20,
            "lengthChange": false,
            "searching": true,
            "ordering": true,
            "info": true,
            "autoWidth": true,
            "responsive": true,
        });

        $('#date_report').daterangepicker({
            timePicker: false,
            timePickerIncrement: 30,
            startDate: '<?php echo isset($_GET['date_report']) ? $date_from : $firstDay; ?>',
            endDate: '<?php echo isset($_GET['date_report']) ? $date_to : $lastDay; ?>',
            locale: {
                format: 'DD/MM/YYYY'
            },
        })

        $('.change-select').change(function(){
            $('#form_search').submit();
        });
    });
    

    function modifyData(type_post, quarterCode, id, quarter) {
        $.ajax({
        type: 'POST',
        url: $(location).attr('href'),
        data: {type_post: type_post, quarterCode: quarterCode, id: id, quarter: quarter},
        success: function(data) {
            if (data != null) {
                $('#action_js').empty();
                $('#action_js').append(data);
            }
        },
        error: function (error) {
            swal.fire({
                title: 'Error: ' + error.statusText,
                text: name,
                icon: 'warning',
                confirmButtonColor: '#3085d6',
                confirmButtonText: 'Ok !',
            })
        }
        });
    }

</script>

<?php
    $this->inlineScript()
    ->prependFile($this->basePath('public/plugins/daterangepicker/daterangepicker.js'))
    ->prependFile($this->basePath('public/plugins/datatables-responsive/js/responsive.bootstrap4.min.js'))
    ->prependFile($this->basePath('public/plugins/datatables-responsive/js/dataTables.responsive.min.js'))
    ->prependFile($this->basePath('public/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js'))
    ->prependFile($this->basePath('public/plugins/datatables/jquery.dataTables.min.js'))
    ->prependFile($this->basePath('public/plugins/select2/js/select2.full.min.js'));
?>