
<?php
    $this->headLink()
	->prependStylesheet($this->basePath('public/plugins/daterangepicker/daterangepicker.css'))
    ->prependStylesheet($this->basePath('public/plugins/datatables-responsive/css/responsive.bootstrap4.min.css'))
    ->prependStylesheet($this->basePath('public/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css'))
    ->prependStylesheet($this->basePath('public/plugins/select2/css/select2.min.css'))
    ->prependStylesheet($this->basePath('public/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css'));

    use Laminas\Session\Container;
    $containerUser = new Container('user');

    $date = new DateTime();
    $firstDay = date('1-m-Y', strtotime('-1 month'));
    $lastDay = $date->modify('last day of this month');

    if (isset($_GET['date_report']) && $_GET['date_report'] != '') {
        $date = explode(" - ", $_GET['date_report']);
        $date_from = date("d-m-Y", strtotime(str_replace('/','-', $date[0]))).' 00:00';
        $date_to = date("d-m-Y", strtotime(str_replace('/','-', $date[1]))).' 23:59';
    }
?>

<?php if (isset($this->params['flashMessages']['success'])) { ?>
    <script type="text/javascript">
        $(document).ready(function() {
            swal.fire({
                title: 'Thành công',
                text: '<?php echo $this->params['flashMessages']['success']; ?>',
                icon: 'success',
                confirmButtonColor: '#3085d6',
                confirmButtonText: 'Ok !',
            })
        });
    </script>
<?php } ?>
<?php if (!isset($job) || $job != null) { ?>
    <div id="action_js"></div>

    <div class="col-12">
        <div class="card card-info">
            <div class="card-body ">
                <form id="form_search" method="get">
                    <div class="row">
                        <div class="col-12 col-md-5 form-group"></div>
                        <div class="col-12 col-md-2 form-group">
                            <label for="jobs">Công việc</label>
                            <select id="jobs" name="jobs" class="form-control custom-select change-select select2bs4">
                                <option value="">---------</option>
                                <?php if ($listJob != null){ foreach ($listJob as $key => $value) { ?>
                                    <option <?php echo isset($_GET['jobs']) && $_GET['jobs'] == $value['id'] ? 'selected' : ''; ?> value="<?php echo $value['id']; ?>"><?php echo $value['job_name']; ?></option>
                                <?php }} ?>
                            </select>
                        </div>
                        <div class="col-12 col-md-5 form-group"></div>
                        
                        <div class="col-12 text-center form-group">
                            <button id="item_search" type="submit" class="btn btn-custom-info"><i class="fa fa-search pr-2"></i>Tìm kiếm</button>
                            <button id="item_search" type="button" class="btn btn-custom-warning" onclick="modifyJob('view_job', '')"><i class="fa fa-plus pr-2"></i>Thêm mới</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="col-12">
        <div class="card card-info">
            <div class="card-body">
                <table id="example2" class="table table-bordered table-hover table-like-striped">
                    <thead class="vera-middle text-center border-top">
                        <tr>
                            <th>{<span class="text-danger">.<?php echo isset($data) ? count($data) : ''; ?>.</span>} #</th>
                            <th>Tên công việc</th>
                            <th>Ca ngày/đêm</th>
                        </tr>
                    </thead>
                    <tbody class="text-left">
                        <?php if (isset($data) && $data != null) { $i=1; foreach ($data as $value){ ?>
                            <tr>
                                <td class="text-center">
                                    <button type="button" class="btn btn-xs btn-custom-primary" onclick="modifyJob('view_job', '<?php echo $value['id']; ?>')"><i class="fa fa-eye pr-1"></i> Sửa</button>
                                    <a href="/<?php echo $value['id']; ?>" class="btn btn-xs btn-custom-danger"><i class="fa fa-cogs pr-1"></i> Cài đặt</a>
                                </td>
                                <td><?php echo $value['job_name']; ?></td>
                                <td class="text-center"><?php echo $value['type_works'] == 0 ? 'Đêm' : ($value['type_works'] == 1 ? 'Ngày' : 'Ngày - PT'); ?></td>
                            </tr>
                        <?php $i++; }} ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
<?php } else { ?>
    <div class="col-12">
        <div class="card card-info">
            <div class="card-body text-center">
                <div class="row">
                    <div class="col-md-4"></div>
                    <div class="col-md-4">
                        <!-- //Check if job is not blank else input -->
                         <form method="post">
                            <input type="text" class="form-control" placeholder="Enter job details here..." value="<?php echo isset($job) ? $job['job_name'] : ''; ?>" name="job_name" id="job_name" required>
                            <input type="hidden" name="id" id="id" value="<?php echo isset($job) ? $job['id'] : ''; ?>">
                            <input type="hidden" name="type_post" id="type_post" value="<?php echo isset($job) ? 'edit_job' : 'add_job'; ?>">
                            <button type="submit" class="btn btn-custom-info"><i class="fa fa-save pr-2"></i>Save Job</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="card card-info">
            <div class="card-body text-center">
                <div class="row">
                    <div id="task-list"></div>
                    <button id="add-line-btn" class="btn btn-custom-primary"><i class="fas fa-plus mr-2"></i>Thêm dòng</button>
                </div>
            </div>
        </div>
    </div>
<?php } ?>


<!-- Page specific script -->
<script type="text/javascript">
    jQuery(document).ready(function($){
        //Initialize Select2 Elements
        $('.select2').select2();

        $('.select2bs4').select2({
            theme: 'bootstrap4'
        })

        $('#example2').DataTable({
            "paging": true,
            "pageLength": 20,
            "lengthChange": false,
            "searching": true,
            "ordering": true,
            "info": true,
            "autoWidth": true,
            "responsive": true,
        });
    });
    
    
    // Hàm để tạo một dòng mới
    function createLine() {
        const lineContainer = document.createElement('div');
        lineContainer.className = 'line-item row align-items-center';

        lineContainer.innerHTML = `
            <div class="col-md-2">
                <label for="loai-xe">Loại xe tải:</label>
                <input type="text" class="form-control" name="loai-xe" placeholder="Loại xe tải 2T, 3T, ...">
            </div>
            <div class="col-md-2">
                <label for="luong-tai-xe">Mức lương tài xế:</label>
                <input type="number" class="form-control" name="luong-tai-xe" placeholder="Lương tài xế">
            </div>
            <div class="col-md-2">
                <label for="luong-phu-xe">Mức lương phụ xe:</label>
                <input type="number" class="form-control" name="luong-phu-xe" placeholder="Lương phụ xe">
            </div>
            <div class="col-md-2">
                <label for="luong-phu-xe">Trợ cấp:</label>
                <input type="number" class="form-control" name="luong-phu-xe" placeholder="Trợ cấp">
            </div>
            <div class="col-md-2">
                <button type="button" class="btn btn-danger mt-4 remove-line">Xóa</button>
            </div>
        `;

        // Thêm sự kiện xóa dòng
        lineContainer.querySelector('.remove-line').addEventListener('click', function() {
            lineContainer.remove();
        });

        return lineContainer;
    }

    // Xử lý sự kiện khi nhấn nút "Thêm dòng"
    document.getElementById('add-line-btn').addEventListener('click', function() {
        const taskList = document.getElementById('task-list');
        const newLine = createLine();
        taskList.appendChild(newLine);
    });

    function modifyJob(type_post, id) {
        $.ajax({
        type: 'POST',
        url: $(location).attr('href'),
        data: {type_post: type_post, id: id},
        success: function(data) {
            if (data != null) {
                $('#action_js').empty();
                $('#action_js').append(data);
            }
        },
        error: function (error) {
            swal.fire({
                title: 'Error: ' + error.statusText,
                text: name,
                icon: 'warning',
                confirmButtonColor: '#3085d6',
                confirmButtonText: 'Ok !',
            })
        }
        });
    }

</script>

<?php
    $this->inlineScript()
    ->prependFile($this->basePath('public/plugins/daterangepicker/daterangepicker.js'))
    ->prependFile($this->basePath('public/plugins/datatables-responsive/js/responsive.bootstrap4.min.js'))
    ->prependFile($this->basePath('public/plugins/datatables-responsive/js/dataTables.responsive.min.js'))
    ->prependFile($this->basePath('public/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js'))
    ->prependFile($this->basePath('public/plugins/datatables/jquery.dataTables.min.js'))
    ->prependFile($this->basePath('public/plugins/select2/js/select2.full.min.js'));
?>